### ISSUE TITLE
.env file is visible with google API credentials

### ISSUE THREAD

**Issue by cmjchrisjones** [Rishi-Sharma2002/consultingWebsite#7]
Hi @Rishi-Sharma2002 - I'd like to mention that it appears you've committed your `.env` file into source control with your API keys, this is typically a bad idea as someone could potentially use these, and if they're for a paid service, could end up racking up a pretty huge bill, therefore it would be worth removing your .env file from source control, adding it to a .git ignore file to prevent further accidental commits, and regenerating your api keys / client secrets once done so they're no longer in the public domain.

If you'd like any more clarification on this please don't hesitate to reach out

**Comment by Acephoeni-X** [comment]
Yeah, thanks for pointing it out. I have removed the .env file. I know it will be shown in the commit history. After the hacktoberfest gets over, I will again make the repository private.

Thanks @cmjchrisjones
